---
name: Install Puppet
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-puppet:
    name: ${{ matrix.collection }} / ${{ matrix.os.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        collection: [ puppet6, puppet7 ]
        os: [
          { name: "CentOS 6", image: "litmusimage/centos:6" },
          { name: "CentOS 7", image: "litmusimage/centos:7" },
          { name: "CentOS 8", image: "litmusimage/centos:8" },
          { name: "Debian 9", image: "litmusimage/debian:9" },
          { name: "Debian 10", image: "litmusimage/debian:10" },
          { name: "Debian 11", image: "litmusimage/debian:11" },
          { name: "Ubuntu 16.04", image: "litmusimage/ubuntu:16.04" },
          { name: "Ubuntu 18.04", image: "litmusimage/ubuntu:18.04" },
          { name: "Ubuntu 20.04", image: "litmusimage/ubuntu:20.04" },
        ]
    container:
      image: ${{ matrix.os.image }}
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install puppet-agent from ${{ matrix.collection }} collection
        run: bash -x test_install.sh -c ${{ matrix.collection }}
